M48
; DRILL file {KiCad 6.0.10-86aedd382b~118~ubuntu22.04.1} date Di 17 Jan 2023 16:43:09 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-17T16:43:09+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10-86aedd382b~118~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
%
G90
G05
T1
X3.937Y-3.9102
T0
M30
