M48
; DRILL file {KiCad 6.0.2-378541a8eb~116~ubuntu20.04.1} date Mi 16 Mär 2022 12:21:39 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-16T12:21:39+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2-378541a8eb~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
%
G90
G05
T1
X3.937Y-3.9877
T0
M30
