M48
; DRILL file {KiCad 6.0.10-86aedd382b~118~ubuntu22.04.1} date Mi 18 Jan 2023 19:19:39 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-18T19:19:39+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10-86aedd382b~118~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
%
G90
G05
T1
X4.8031Y-3.7008
X8.0709Y-3.7598
T0
M30
