M48
; DRILL file {KiCad 7.0.10} date Di 16 Jan 2024 16:55:52 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-16T16:55:52+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1319
%
G90
G05
T1
X4.765Y-3.7231
X4.765Y-4.6287
X7.0485Y-3.7231
X7.0485Y-4.6287
T2
X6.3764Y-4.3127
X6.7764Y-4.3127
M30
